server:
  port: 8891
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    healthcheck:
      enabled: true

#redis配置
redis:
  host: 127.0.0.1
  port: 6379
  pool:
    max-active: -1
    max-idle: 20
    max-wait: 1000000
  timeout: 1000000
